export default () => ({
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  JWT_REFRESH_TOKEN_KEY: process.env.JWT_REFRESH_TOKEN_KEY,

  INTERPARK_MUSICAL_URL: process.env.INTERPARK_MUSICAL_URL,
  INTERPARK_CONCERT_URL: process.env.INTERPARK_CONCERT_URL,

  YES24_MUSICAL_URL: process.env.YES24_MUSICAL_URL,
  YES24_CONCERT_URL: process.env.YES24_CONCERT_URL,

  TICKETLINK_MUSICAL_URL: process.env.TICKETLINK_MUSICAL_URL,
  TICKETLINK_CONCERT_URL: process.env.TICKETLINK_CONCERT_URL,

  MELON_MUSICAL_URL: process.env.MELON_MUSICAL_URL,
  MELON_CONCERT_URL: process.env.MELON_CONCERT_URL,
});
